services:
  - type: web
    name: DarkChoices
    env: docker
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget
      wget https://dot.net/v1/dotnet-install.sh
      bash dotnet-install.sh --channel LTS
      export PATH=$PATH:/root/.dotnet
      /root/.dotnet/dotnet publish -c Release -o out ./BulkyBookWeb/BulkyBookWeb.csproj
    startCommand: /root/.dotnet/dotnet out/BulkyBookWeb.dll
